project:
  type: website
  output-dir: docs

website:
  title: "Max Nghiem Lee"
  navbar:
    left:
      - href: accomplishments.qmd
        text: Accomplishments
      - href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



